### ISSUE TITLE
Dupes if multiple have on same webhook and also <img=2> etc showing.

### ISSUE THREAD

**Issue by Haavardaw** [pascalla/clan-chat-webhook#1]
Hey currently there are duplicates if multiple people have the plugin on. Could a check for duplicates if the same clan be checked or something? I want multiple people in a clan to have plugin on to monitor chat always. Without having it spam dupes.

Also it shows stuff like <img=2> for I'd assume irons? then stuff like <img=142><col=7f0000>Justinsiron has left.</col> for when people leave or join clan
![image](https://github.com/pascalla/clan-chat-webhook/assets/72413703/c0264f44-91ea-4243-8bda-455d4f66f675)

**Comment by Haavardaw** [comment]
![image](https://github.com/pascalla/clan-chat-webhook/assets/72413703/09080bbf-f382-40f8-95b8-af4987da9c8b)
Here are my settings

**Comment by pascalla** [comment]
@Haavardaw Sadly this is an unfortunate side effect of runelite plugins not aware of eachother meaning it can not dedupe messages with the plugin alone.

However I am using this plugin for the exact same use case as you, currently I use my [https://github.com/pascalla/clan-chat-webhook-server](https://github.com/pascalla/clan-chat-webhook-server) repo and host a little webserver that does the filtering and replacement of icons. 

I understand you might not have the knowledge to host/run this little server, I have been working on making this much more friendly so anyone can set it up, working similary to how the shooting star plugin works. 

I hope to have this finished within the next two weeks (and then some time for RuneLite plugin to be reviewed/approved). 

In the meantime if you really wanna get this working I can set up the server quickly (and for free) so you use it as intended. Feel free to add me on Discord Jhawsh#0001 and you can send me the Discord webhook url and i'll send you the webhook URL for to put in the plugin.

**Comment by pascalla** [comment]
Plugin has been updated to use a centralised system, https://clanchat.net/

Feel free to use my hosted version, or you can host your own

https://github.com/pascalla/clanchat.net
