### ISSUE TITLE
Clan Announcements

### ISSUE THREAD

**Issue by Osamu01** [pascalla/clan-chat-webhook#11]
I believe putting announcements such as level ups, etc should be formatted in bold or something to easier tell. that or you could put something like this in front of it. 
![800px-Dungeon_entrance_logo](https://github.com/pascalla/clan-chat-webhook/assets/35316988/dd561cad-7ddd-44fb-8c90-86272a53ede3)

**Comment by pascalla** [comment]
I've added icons for the different type of broadcasts, they are toggleable via a new setting, going to see how the icons fit in to see if they need to be changed.

![image](https://github.com/pascalla/clan-chat-webhook/assets/22846433/7e342fbe-8e19-41a9-8101-b9c02ac10df0)

**Comment by Ryglus** [comment]
> I've added icons for the different type of broadcasts, they are toggleable via a new setting, going to see how the icons fit in to see if they need to be changed.

This new feature is broken since you cant disable it, i think that on server level you dont have correct naming as the name that is being checked/required.

ai this makes it so you can really update any change at all.

**Comment by pascalla** [comment]
> > I've added icons for the different type of broadcasts, they are toggleable via a new setting, going to see how the icons fit in to see if they need to be changed.
> 
> This new feature is broken since you cant disable it, i think that on server level you dont have correct naming as the name that is being checked/required.
> 
> ai this makes it so you can really update any change at all.
> 
> ![image](https://user-images.githubusercontent.com/103588468/265281252-e524bd11-ba26-4029-8011-6f2cbf53bac5.png)
> 
> ![image](https://user-images.githubusercontent.com/103588468/265281269-b31f9569-bf61-4175-aaa6-4ca9762961a5.png)

Just pushed a fix, just a typo between clan_icons and clain_icons in validation logic. Let me know if this fixes it :)

**Comment by Ryglus** [comment]
> > > I've added icons for the different type of broadcasts, they are toggleable via a new setting, going to see how the icons fit in to see if they need to be changed.
> > 
> > 
> > This new feature is broken since you cant disable it, i think that on server level you dont have correct naming as the name that is being checked/required.
> > ai this makes it so you can really update any change at all.
> > ![image](https://user-images.githubusercontent.com/103588468/265281252-e524bd11-ba26-4029-8011-6f2cbf53bac5.png)
> > ![image](https://user-images.githubusercontent.com/103588468/265281269-b31f9569-bf61-4175-aaa6-4ca9762961a5.png)
> 
> Just pushed a fix, just a typo between clan_icons and clain_icons in validation logic. Let me know if this fixes it :)

Yep, perfect, fixed, thank you

**Comment by Osamu01** [comment]
Just got wind of this, how exciting! I will let you know if I have further suggestions.
