### ISSUE TITLE
Not receiving messages via webhook

### ISSUE THREAD

**Issue by Not-Ur-Hero** [pascalla/clan-chat-webhook#4]
After the update, I've stopped receiving messages to my webhook. I have gone through and configured it as per the new update. I have also tried re-installing & deleting/re-creating the webhook but still no messages are coming through. 

Screenshot of settings:
![cc-webhook](https://github.com/pascalla/clan-chat-webhook/assets/90741640/e95aae4f-aeeb-47d4-bf06-6450120c81bb)

**Comment by pascalla** [comment]
Hey,

The V2 update it easier for the plugin to be used multiple people in one clan without getting duplicates. Resulting in better coverage overall for clan messages in your discord.

You can use https://clanchat.net/ (or self host https://github.com/pascalla/clanchat.net) to get the same functionality. 

To get this working with https://clanchat.net/ sign in, create clan and put the discord webhook link in the settings and click update.

![image](https://github.com/pascalla/clan-chat-webhook/assets/22846433/a9abb474-01b0-46c1-9a8d-0ae2a4709f1c)

You then can generate a key for the plugin below the settings

![image](https://github.com/pascalla/clan-chat-webhook/assets/22846433/2fb0f6fd-7993-4e69-934c-763c12b2d97e)

Runelite plugin settings would look like this

![image](https://github.com/pascalla/clan-chat-webhook/assets/22846433/74544964-231b-4283-a95c-93f99efd9294)

If you are still having problems let me know.

**Comment by Not-Ur-Hero** [comment]
Ahh I see, thank you!
