### ISSUE TITLE
Plugin not sending to webhook

### ISSUE THREAD

**Issue by CANFGhost** [pascalla/clan-chat-webhook#5]
We enabled the plugin and tried every possible configuration, but the plugin does not send a message to the webhook.
The Webhook was manually tested and receives messages.
Entering the Webhook manually into the Plugins "Webhook Endpoint" does not work, using the secret key does not work after making a clan on clanchat.net (what else would you enter into Webnhook Endpoint when using the Clanchat.net?)

I can't figure it out after the update.

**Comment by pascalla** [comment]
Please see 

https://github.com/pascalla/clan-chat-webhook/issues/4#issuecomment-1566158722
