### ISSUE TITLE
Special raid drops doesnt send a message in discord

### ISSUE THREAD

**Issue by Ryglus** [pascalla/clan-chat-webhook#7]
> Someone recieved special loot from a raid: *

Is ignored, maybe oversight or maybe its recent addition.

**Comment by pascalla** [comment]
I seem to have made a spelling mistake

https://github.com/pascalla/clan-chat-webhook/blob/b95215134a58ef3ae9521ea9582203f539408973/src/main/java/com/clanchatwebhook/ClanChatWebhookPlugin.java#L133

Will get a fix in. Cheers

**Comment by Ryglus** [comment]
Will this change come to the https://clanchat.net/ aswell?
