### ISSUE TITLE
Suddenly not receiving webhook messages

### ISSUE THREAD

**Issue by s0lved** [pascalla/clan-chat-webhook#8]
A few hours ago I was receiving messages in my discord with this plugin, however it has suddenly stopped working. I've tried reinstalling the plugin, adding in a new webhook, deleting and readding a new secret key but it still does not work. The endpoint URL is set to  "https://clanchat.net" so I don't think this is the issue.

**Comment by pascalla** [comment]
Apologies, There was an issue on my site (https://clanchat.net) which stopped messages going through. This should be resolved now, and i'm looking into the issue to make sure it doesn't happen again.

**Comment by s0lved** [comment]
Thank you! It's working now :)
